M48
; DRILL file {KiCad 9.0.8-9.0.8~ubuntu24.04.1} date 2026-04-14T18:53:28+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-04-14T18:53:28+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8-9.0.8~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.15Y-4.275
X2.3Y-3.65
X2.35Y-2.425
X3.575Y-1.675
M30
